### ISSUE TITLE
Server Crash (java.lang.NoSuchMethodError: 'net.minecraft.item.ItemStack net.minecraft.item.Item.func_190903_i()')

### ISSUE THREAD

**Issue by aking4125** [Jboymercs/nether_backport#11]
Hello,

On a multiplayer server, upon entering the nether near any piglin. The server crashes with the following report if a player is near a piglin mob: 
[crash-2024-10-14_22.35.46-server.txt](https://github.com/user-attachments/files/17371807/crash-2024-10-14_22.35.46-server.txt)
[2024-10-14-7.log.gz](https://github.com/user-attachments/files/17371813/2024-10-14-7.log.gz)

We are using [Cleanroom](https://github.com/CleanroomMC/Cleanroom) if anything. Any ideas?

**Comment by Jboymercs** [comment]
Thanks for the report! a fix update will come within the week
