### ISSUE TITLE
Crash in loading minecraft

### ISSUE THREAD

**Issue by Tihonya76** [Jboymercs/nether_backport#12]
[latest.log](https://github.com/user-attachments/files/17510831/latest.log)
[modlist.txt](https://github.com/user-attachments/files/17510836/modlist.txt)

**Comment by Tihonya76** [comment]
I hope there is a bug and I can add the mod to myself

**Comment by Jboymercs** [comment]
You need Nether - API installed [https://modrinth.com/mod/nether-api](url)
