### ISSUE TITLE
About twisting_vines

### ISSUE THREAD

**Issue by sui-ke** [Jboymercs/nether_backport#14]
https://github.com/user-attachments/assets/6a2c843f-a99a-48e9-bb34-c6a4e985d3d8

- In addition, it will automatically climb up when it encounters twisting_vines.

**Comment by Jboymercs** [comment]
Fixed in 0.4, get it here -> [https://www.curseforge.com/minecraft/mc-mods/unseens-nether-backport/files/5857854](url)
