### ISSUE TITLE
Minor bugs

### ISSUE THREAD

**Issue by darkheadmaster132** [Jboymercs/nether_backport#5]
just some really small bugs that i found while testing the mod, they aren't game breaking or anything but still, just letting you know

-Piglins and all of it variants have really big knock back resistance
-Soul lantern does not do block updates after being placed
-Warped and Crimson fungus do not drop while block is mined under them (In vanilla MC they always drop)
-Warped and crimson roots and vines do not drop themselves when mined
-All of crimson and warped (roots, fungus and sprouts) do not do block update after being placed (excluding vines)
-Any block that is placed on the nylium turns it into netherrack (In vanilla only full blocks turn nylium into netherrack)
-Fungus turns into a tree only when placed in the specific block in the world otherwise it turns into air (I don't understand it either)
-Overabundance of the blackstone in the nether (In vanilla it spawns under the lava level)

**Comment by Jboymercs** [comment]
Appreciated for the feedback, I'll note these bugs down!

**Comment by Jboymercs** [comment]
Fixed in 0.4, get it here -> [https://www.curseforge.com/minecraft/mc-mods/unseens-nether-backport/files/5857854](url)
