### ISSUE TITLE
Config boundaries for nether portal world gen (and completely disabling them) for version 0.3

### ISSUE THREAD

**Issue by darchitectlp** [Jboymercs/nether_backport#8]
Is there a way to completely disable the nether portals spawning? The config only mentions "higher means less" with no indication of the limits... If I want zero portals spawning in world gen, do I say 1000? 10,000? 

Absolutely amazing work here, by the way. Just awesome. Thanks!

**Comment by Jboymercs** [comment]
theres currently no way to disable them, but that'll be in the following update, as a temp fix yes, you can just set the number to 90000 and you'll practically never see them

**Comment by Jboymercs** [comment]
Fixed in 0.4, get it here -> [https://www.curseforge.com/minecraft/mc-mods/unseens-nether-backport/files/5857854](url)
